galaxy_info:
  author: Danilo Cerdas
  description: Baseline security hardening for cloud instances
  company: Personal Projects
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
dependencies: []
